### ISSUE TITLE
Update for Emacs 24

### ISSUE THREAD

**Issue by michaelsbradleyjr** [dz/ir_black_emacs#1]
Hi, I've been exploring a switch from MacVim to Emacs and one of the things I miss, which would make me feel a bit more at home, is the `ir_black` color theme.

I used Mac homebrew to install GNU Emacs, which gave me version 24.  Your port of the `ir_black` color scheme doesn't work for this newer branch of Emacs.

Would you consider creating an updated version which is compatible with the 24 branch?

I'm a bit too novice with elisp (only a few days into Emacs at the present) to attempt it myself.

**Comment by dz** [comment]
I've updated this with the current version I use
